### PR TITLE
Puppy coin investment thesis

### PR DESCRIPTION
**Pull request by puppycoin69**
much wow very invest

### CODE REVIEW

**Comment by 52081** [comment]
Very interesting investment thesis!

**Comment by puppycoin69** [comment]
much iteration
our very own [DataPUP](https://twitter.com/PuppycoinData?s=20) is working on some additions that will be available shortly

**Comment by rencryptofish** [comment]
what about a mechanism to kick back value to meme coin dao?

**Comment by puppycoin69** [comment]
> what about a mechanism to kick back value to meme coin dao?

definitely some ideas brewing in the community about this

**Comment by walkentalk** [comment]
can u stake puppycoin for more puppycoin? if not add that

**Comment by puppycoin69** [comment]
> can u stake puppycoin for more puppycoin? if not add that

the supply of Puppy Coin is fixed, so that mechanism can't exist unless some whales donate PUP which is unlikely

**Pull request closed without merging**
